connector.name=mysql
connection-url=jdbc:mysql://8.134.89.163:3306?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&generateSimpleParameterMetadata=true
connection-user=root
connection-password=gantecwgs
